ALTER TABLE message ADD COLUMN reply_to_id BIGINT NULL;
ALTER TABLE message ADD COLUMN reply_to_content VARCHAR(100) NULL;
ALTER TABLE message ADD COLUMN reply_to_sender VARCHAR(50) NULL;
ALTER TABLE message ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';
