apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messaging-engine

resources:
  - namespace.yml
  - configmap.yml
  - secret.yml
  - gateway-service.yml
  - chat-service.yml
  - query-service.yml
  - presence-service.yml
  - notification-service.yml
  - ai-service.yml
  - ingress.yml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
