# Dev environment overrides
global:
  imageTag: e70248447f3a55195e57afc2bfe8781c256f9c83

services:
  gateway:
    replicas: 2
  chat:
    replicas: 2

config:
  esEnabled: "true"
  tracingEnabled: "true"
